INTERNAL_BPM = 120

MAX_NUM_STEPS  = 32
NUM_STEP_PAGES = 2
NOTE_LEN_SEC   = 0.04

USE_EXT_CLOCK = True

CONTROLLER_PORT_NAME = 'Launchpad'
DRUM_OUT_PORT_NAME   = 'loopMIDI'
EXT_CLOCK_PORT_NAME  = 'Live'
